name: CI

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install
        run: npm install

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build
